sudo: require
language: bash

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y texlive-xetex texlive-latex-recommended texlive-latex-extra texlive-base texlive-latex-base texlive-lang-french

script:
    - bash build.sh

after_success:
    - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
    - chmod +x send.sh
    - ./send.sh success $WEBHOOK_URL

after_failure:
    - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
    - chmod +x send.sh
    - ./send.sh failure $WEBHOOK_URL

deploy:
    provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file: "main/henriette_jidouard_milis_2018_19_MEMOIRE MEEF.pdf"
    skip_cleanup: true
    draft: true
